import { useEffect, useMemo, useState } from 'react';
import type { ContextHandoff, HandoffRecord } from '@ucad/contracts';
import { useI18n, useT } from '../i18n-context';
import {
  HANDOFF_SECTIONS,
  availableSections,
  sectionLabelKey,
  type HandoffSection,
} from '../../../shared/handoff-prompt';

/**
 * Handoff — the artefact that carries state to the *next* agent.
 *
 * This is deliberately NOT "memory self-learning". Nothing
 * here infers anything. It is a readable, editable, copyable record of what
 * this session actually did, so a different agent (or a different human) can
 * pick the work up without re-explaining the architecture, the failed attempts
 * and the open questions.
 *
 * Design constraints:
 *  - readable, not an opaque row  → plain sections, no database
 *  - supersede, never destroy    → the previous handoff is kept by the caller
 *  - zero LLM                    → generated by Main from the event log alone
 */

export interface HandoffPanelProps {
  handoff: ContextHandoff | null;
  /** The session's handoff chain, newest first. Empty when there is none yet. */
  history: HandoffRecord[];
  busy: boolean;
  onRegenerate: () => void;
  /**
   * Which parts of the record go into the next session.
   *
   * The sections are passed rather than looked up here so this component stays
   * a view: what ends up in the prompt is decided by one tested function, not
   * reassembled at a call site.
   */
  onStartWithHandoff: (handoff: ContextHandoff, sections: HandoffSection[]) => void;
  onClaim: (handoffId: string) => void;
  onComplete: (handoffId: string) => void;
  hasSession: boolean;
}

/** Reads a possibly-absent list without throwing. */
function list<T>(value: T[] | undefined): T[] {
  return Array.isArray(value) ? value : [];
}

export function HandoffPanel({
  handoff,
  history,
  busy,
  onRegenerate,
  onStartWithHandoff,
  onClaim,
  onComplete,
  hasSession,
}: HandoffPanelProps): JSX.Element {
  const t = useT();
  const { locale } = useI18n();
  const [copied, setCopied] = useState(false);
  /*
   * The carry selection. Seeded from the record itself, and re-seeded whenever
   * a different handoff arrives, because a selection that survived a
   * regeneration would silently carry a mix of two records' sections.
   */
  const [selected, setSelected] = useState<HandoffSection[]>([]);
  const carriable = useMemo(
    () => (handoff ? availableSections(handoff) : []),
    [handoff],
  );
  useEffect(() => {
    setSelected(carriable);
  }, [carriable]);

  const toggle = (section: HandoffSection) => {
    setSelected((current) =>
      current.includes(section)
        ? current.filter((entry) => entry !== section)
        : // Keep the canonical order no matter how the boxes were ticked, so the
          // document stays diffable between runs.
          HANDOFF_SECTIONS.filter((entry) => [...current, section].includes(entry)),
    );
  };

  // A handoff may come from an older Main or a partial record. Reading a
  // missing array must not blank the panel — a handoff that renders to nothing
  // is worse than one that renders partially.
  const files = list(handoff?.relevantFiles);
  const decisions = list(handoff?.decisions);
  const changes = list(handoff?.changes);
  const commands = list(handoff?.commandsRun);
  const pendingWork = list(handoff?.pendingWork);
  const cautions = list(handoff?.cautions);

  const markdown = handoff ? toMarkdown(handoff) : '';

  const copy = () => {
    if (!markdown) return;
    // `navigator.clipboard` is unavailable on a non-secure origin, which is the
    // case in the packaged Electron renderer (file://). Failing silently here
    // would look like a broken button, so the state simply does not flip.
    void navigator.clipboard
      .writeText(markdown)
      .then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 2500);
      })
      .catch(() => setCopied(false));
  };

  return (
    <div className="pane">
      <div className="pane-head">
        <h1>{t('handoff.title')}</h1>
        <p>{t('handoff.subtitle')}</p>
      </div>

      {!hasSession && <div className="notice">{t('handoff.noSession')}</div>}

      {!handoff && hasSession && (
        <div className="empty-block">
          <p>{t('handoff.empty')}</p>
          <button className="primary" onClick={onRegenerate} disabled={busy}>
            {busy ? t('common.loading') : t('handoff.generate')}
          </button>
        </div>
      )}

      {handoff && (
        <>
          {history.length > 0 && (
            <div className="card" style={{ marginBottom: 12 }}>
              <h2>{t('handoff.history')}</h2>
              <div className="faint" style={{ fontSize: 11.5, marginBottom: 8 }}>
                {t('handoff.historyHint')}
              </div>
              {/*
                Newest first, because the question this answers is "which one
                am I looking at, and has someone already taken it". An older
                entry is still readable — nothing here is destructive — but it
                is never the one a new agent should resume from.
              */}
              {history.map((record) => (
                <div
                  key={record.id}
                  className="row-gap"
                  style={{ padding: '4px 0', alignItems: 'center' }}
                >
                  <span className="mono faint" style={{ fontSize: 11 }}>
                    #{record.sequence}
                  </span>
                  <span
                    className={
                      record.state === 'done'
                        ? 'badge ok'
                        : record.state === 'claimed'
                          ? 'badge warn'
                          : 'badge'
                    }
                  >
                    {t(`handoff.state_${record.state}`)}
                  </span>
                  {record.claimedBy && (
                    <span className="faint" style={{ fontSize: 11 }}>
                      {t('handoff.claimedBy', { agent: record.claimedBy })}
                    </span>
                  )}
                  {record.supersededBy && (
                    <span className="faint" style={{ fontSize: 11 }}>
                      {t('handoff.superseded')}
                    </span>
                  )}
                  {/*
                    The action belongs to the newest entry only. Offering
                    "认领" on a superseded handoff would be offering to take
                    ownership of work that has already been replaced, and the
                    store would happily allow it.
                  */}
                  {!record.supersededBy && record.state === 'open' && (
                    <button className="ghost" onClick={() => onClaim(record.id)} disabled={busy}>
                      {t('handoff.claim')}
                    </button>
                  )}
                  {!record.supersededBy && record.state === 'claimed' && (
                    <button
                      className="ghost"
                      onClick={() => onComplete(record.id)}
                      disabled={busy}
                    >
                      {t('handoff.markDone')}
                    </button>
                  )}
                </div>
              ))}
            </div>
          )}

          <div className="row" style={{ display: 'flex', gap: 8, marginBottom: 12 }}>
            <button className="primary" onClick={onRegenerate} disabled={busy}>
              {busy ? t('common.loading') : t('handoff.regenerate')}
            </button>
            <button onClick={copy}>{copied ? t('handoff.copied') : t('handoff.copy')}</button>
          </div>

          {/*
           * What gets carried, chosen by the user.

           * This used to be a single button that carried the objective and
           * nothing else, which threw away the decisions, the failed commands
           * and the open work — the three things the
           * user should not have to repeat. The default is everything that has
           * content, because the promise is "you do not have to re-explain
           * yourself"; choosing less is the deliberate act, and a section with
           * nothing in it is not offered at all.
           */}
          {carriable.length > 0 && (
            <div className="card" style={{ marginBottom: 12 }}>
              <h2>{t('handoff.carryTitle')}</h2>
              <p className="faint" style={{ marginTop: 0 }}>
                {t('handoff.carryHint')}
              </p>
              <div className="handoff-carry">
                {carriable.map((section) => (
                  <label className="check" key={section}>
                    <input
                      className="checkbox"
                      type="checkbox"
                      checked={selected.includes(section)}
                      onChange={() => toggle(section)}
                    />
                    <span>{t(sectionLabelKey(section))}</span>
                  </label>
                ))}
              </div>
              <button
                className="primary"
                style={{ marginTop: 10 }}
                disabled={selected.length === 0}
                onClick={() => onStartWithHandoff(handoff, selected)}
              >
                {t('handoff.startNew')}
              </button>
              {selected.length === 0 && (
                <p className="faint" style={{ marginBottom: 0 }}>
                  {t('handoff.carryNothing')}
                </p>
              )}
            </div>
          )}

          <div className="handoff-doc">
            <Section title={t('handoff.objective')}>
              <p>{handoff.objective || t('common.none')}</p>
            </Section>

            <Section title={t('handoff.state')}>
              <p>{handoff.currentState || t('common.none')}</p>
            </Section>

            <Section title={t('handoff.relevantFiles')} count={files.length}>
              {files.length === 0 ? (
                <p className="faint">{t('common.none')}</p>
              ) : (
                <ul className="handoff-list">
                  {files.map((entry) => (
                    <li key={entry.path}>
                      <code>{entry.path}</code>
                      <span className="faint"> — {entry.reason}</span>
                    </li>
                  ))}
                </ul>
              )}
            </Section>

            <Section title={t('handoff.decisions')} count={decisions.length}>
              {decisions.length === 0 ? (
                <p className="faint">{t('common.none')}</p>
              ) : (
                <ul className="handoff-list">
                  {decisions.map((decision, i) => (
                    <li key={`${i}-${decision.slice(0, 12)}`}>{decision}</li>
                  ))}
                </ul>
              )}
            </Section>

            <Section title={t('handoff.changes')} count={changes.length}>
              {changes.length === 0 ? (
                <p className="faint">{t('common.none')}</p>
              ) : (
                <ul className="handoff-list">
                  {changes.map((change) => (
                    <li key={change.path}>
                      <code>{change.path}</code>
                      <span className="faint"> — {change.summary}</span>
                    </li>
                  ))}
                </ul>
              )}
            </Section>

            <Section title={t('handoff.commands')} count={commands.length}>
              {commands.length === 0 ? (
                <p className="faint">{t('common.none')}</p>
              ) : (
                <ul className="handoff-list">
                  {commands.map((cmd, i) => (
                    <li key={`${i}-${cmd.command.slice(0, 12)}`}>
                      <code>{cmd.command}</code>
                      <span className="faint"> — {cmd.result}</span>
                    </li>
                  ))}
                </ul>
              )}
            </Section>

            <Section title={t('handoff.pending')} count={pendingWork.length}>
              {pendingWork.length === 0 ? (
                <p className="faint">{t('common.none')}</p>
              ) : (
                <ul className="handoff-list">
                  {pendingWork.map((item, i) => (
                    <li key={`${i}-${item.slice(0, 12)}`}>{item}</li>
                  ))}
                </ul>
              )}
            </Section>

            <Section title={t('handoff.cautions')} count={cautions.length}>
              {cautions.length === 0 ? (
                <p className="faint">{t('common.none')}</p>
              ) : (
                <ul className="handoff-list">
                  {cautions.map((item, i) => (
                    <li key={`${i}-${item.slice(0, 12)}`}>{item}</li>
                  ))}
                </ul>
              )}
            </Section>

            <p className="faint handoff-meta">
              {handoff.producedBy
                ? t('handoff.producedBy', {
                    agent: handoff.producedBy.agentId,
                    at: new Date(handoff.producedBy.at).toLocaleString(locale),
                  })
                : t('common.unknown')}
            </p>
          </div>
        </>
      )}
    </div>
  );
}

function Section({
  title,
  count,
  children,
}: {
  title: string;
  count?: number;
  children: React.ReactNode;
}): JSX.Element {
  return (
    <section className="handoff-section">
      <h3 className="block-title">
        {title}
        {count !== undefined && <span className="count">{count}</span>}
      </h3>
      {children}
    </section>
  );
}

/**
 * Portable form — this is what another agent or a teammate actually reads.
 *
 * Defensive on purpose: a handoff can come from an older Main, from a future
 * schema, or from a partially-written record. Every list is optional-treated
 * because throwing here would blank the whole panel over a missing array.
 */
export function toMarkdown(handoff: ContextHandoff): string {
  const lines: string[] = [];
  const add = (heading: string, items: string[]) => {
    if (items.length === 0) return;
    lines.push(`## ${heading}`, '');
    for (const item of items) lines.push(`- ${item}`);
    lines.push('');
  };

  const producedBy = handoff.producedBy;
  const by = producedBy
    ? `_Produced by ${producedBy.agentId} at ${producedBy.at}_`
    : '_Producer unknown_';

  lines.push(`# ${handoff.objective || 'Session handoff'}`, '');
  lines.push('## Current state', '', handoff.currentState || '_none recorded_', '');
  add(
    'Relevant files',
    list(handoff.relevantFiles).map((f) => `\`${f.path}\` — ${f.reason}`),
  );
  add('Decisions', list(handoff.decisions));
  add('Changes', list(handoff.changes).map((c) => `\`${c.path}\` — ${c.summary}`));
  add(
    'Commands run',
    list(handoff.commandsRun).map((c) => `\`${c.command}\` — ${c.result}`),
  );
  add('Pending work', list(handoff.pendingWork));
  add('Cautions', list(handoff.cautions));
  lines.push('---', by);
  return lines.join('\n');
}
